title: "My Portfolio"
description: "Personal portfolio using the Beckham theme"
baseurl: "" # Leave blank if deploying to root
url: "https://saraschandra9996.github.io"

# Disable Jekyll theme
theme: null
